export const EP = {
  AUTH_LOGIN: '/api/auth/login',
  AUTH_LOGOUT: '/api/auth/logout',
  AUTH_DEVICE_VERIFY: '/api/auth/device/verify',
  THREADS: '/v1/threads',
  THREAD_MESSAGES: (id: string) => `/v1/threads/${id}/messages`,
  FILES: '/v1/files',
  WORKSPACES: '/v1/workspaces',
  WORKSPACES_TREE: '/v1/workspaces/tree',
  WORKSPACES_SEARCH: '/v1/workspaces/search',
  WORKSPACE_NODE: (id: string) => `/v1/workspaces/${id}`,
  WORKSPACE_CONTENT: (id: string) => `/v1/workspaces/${id}/content`,
  WORKSPACE_SHARE: (id: string) => `/v1/workspaces/${id}/share`,
  WORKSPACE_UNSHARE: (id: string) => `/v1/workspaces/${id}/unshare`,
  WORKSPACE_MOVE: (id: string) => `/v1/workspaces/${id}/move`,
  WORKSPACE_RENAME: (id: string) => `/v1/workspaces/${id}/rename`,
  WORKSPACE_TAGS: (id: string) => `/v1/workspaces/${id}/tags`,
  WORKSPACES_FILTER: '/v1/workspaces/filter',
  CAPABILITIES: '/v1/capabilities',
  CAPABILITIES_SEARCH: '/v1/capabilities/search',
  UI_STREAM: '/ui/stream',
  UI_UPLOAD: '/ui/upload',
  UI_EXTRACT_INVOICE: '/ui/extract-invoice',
} as const;
