export const EP = {
  THREADS: '/v1/threads',
  THREAD_MESSAGES: (id: string) => `/v1/threads/${id}/messages`,
  CAPABILITIES: '/v1/capabilities',
  WORKSPACES: '/v1/workspaces',
  WORKSPACES_TREE: '/v1/workspaces/tree',
  WORKSPACES_SEARCH: '/v1/workspaces/search',
  WORKSPACE_NODE: (id: string) => `/v1/workspaces/${id}`,
  WORKSPACE_CONTENT: (id: string) => `/v1/workspaces/${id}/content`,
  WORKSPACE_SHARE: (id: string) => `/v1/workspaces/${id}/share`,
  WORKSPACE_UNSHARE: (id: string) => `/v1/workspaces/${id}/unshare`,
  WORKSPACE_MOVE: (id: string) => `/v1/workspaces/${id}/move`,
  UI_STREAM: '/ui/stream',
  UI_UPLOAD: '/ui/upload',
  UI_EXTRACT_INVOICE: '/ui/extract-invoice',
  FILES: (id: string) => `/v1/files/${id}`,
} as const;
