// Utility
export { cn } from "./utils/cn.js";
export type { WithElementRef } from "./utils/cn.js";

// Primitives (shadcn-svelte, generated by CLI)
export * as Avatar from "./components/ui/avatar/index.js";
export * as Button from "./components/ui/button/index.js";
export * as DropdownMenu from "./components/ui/dropdown-menu/index.js";
export * as Empty from "./components/ui/empty/index.js";
export * as Input from "./components/ui/input/index.js";
export * as ScrollArea from "./components/ui/scroll-area/index.js";
export * as Separator from "./components/ui/separator/index.js";
export * as Sheet from "./components/ui/sheet/index.js";
export * as Sidebar from "./components/ui/sidebar/index.js";
export * as Skeleton from "./components/ui/skeleton/index.js";
export * as Sonner from "./components/ui/sonner/index.js";
export * as Textarea from "./components/ui/textarea/index.js";
export * as Tooltip from "./components/ui/tooltip/index.js";

// Product components
export { default as AppShell } from "./components/app/app-shell.svelte";
export { default as AppSidebar } from "./components/app/app-sidebar.svelte";
export { default as AppNavigationSidebar } from "./components/app/app-navigation-sidebar.svelte";
export { default as AppJobsSidebar } from "./components/app/app-jobs-sidebar.svelte";
export { default as AppMobileHeader } from "./components/app/app-mobile-header.svelte";
export { default as AppMain } from "./components/app/app-main.svelte";
export { default as AppSafeArea } from "./components/app/app-safe-area.svelte";
export { default as AiToolProgress } from "./components/app/ai-tool-progress.svelte";
export type {
  AiToolProgressSize,
  AiToolProgressState,
  AiToolProgressVariant
} from "./components/app/ai-tool-progress.svelte";

export { default as ChatBreadcrumb } from "./components/chat/chat-breadcrumb.svelte";
export { default as ChatComposer } from "./components/chat/chat-composer.svelte";
export { default as ChatEmptyState } from "./components/chat/chat-empty-state.svelte";
export { default as ChatThread } from "./components/chat/chat-thread.svelte";
export { default as ChatMessage } from "./components/chat/chat-message.svelte";
export { default as ChatMessageList } from "./components/chat/chat-message-list.svelte";
export { default as ChatStreamStatus } from "./components/chat/chat-stream-status.svelte";
export { default as ToolEventRow } from "./components/chat/tool-event-row.svelte";
export { default as RoutingMetaRow } from "./components/chat/routing-meta-row.svelte";

export { default as WorkspaceTree } from "./components/workspace/workspace-tree.svelte";
export { default as WorkspaceSmartViews } from "./components/workspace/workspace-smart-views.svelte";
export { default as WorkspaceCommandPalette } from "./components/workspace/workspace-command-palette.svelte";
export { default as WorkspaceFilingSuggestion } from "./components/workspace/workspace-filing-suggestion.svelte";
export type { PaletteCommand } from "./components/workspace/workspace-command-palette.svelte";
export { default as WorkspaceSwitcher } from "./components/workspace/workspace-switcher.svelte";
export { default as WorkspaceNodeRow } from "./components/workspace/workspace-node-row.svelte";
export { default as WorkspaceDocPeek } from "./components/workspace/workspace-doc-peek.svelte";

export { default as AccountMenu } from "./components/account/account-menu.svelte";
export { default as UserAvatar } from "./components/account/user-avatar.svelte";
export { default as AuthOnboardingPanel } from "./components/account/auth-onboarding-panel.svelte";
